### ISSUE TITLE
Authenticating Tuya app not working

### ISSUE THREAD

**Issue by HeMaN-NL** [tuya/tuya-smart-life#17]
Added Smartlife through HACS to Home Assistant, but when trying to add the authorization for Home Assistant by scanning the QR code in the Tuya Smart app I get:
"please use the designated app to scan the code to log in"

I copied the user code from the app, so I am sure I am using the right code.

Any way to work around or debug this?

Edit: Account in the Netherlands if this might matter

**Comment by shihuimiao** [comment]
Not support Tuya Smart app, Only supports Smart Life app.

**Comment by caideone** [comment]
> 不支持涂鸦智能应用，仅支持智能生活应用。

后期会支持涂鸦应用吗，还有国内一大堆涂鸦oem app

**Comment by tvogel** [comment]
It seems, allowing Tuya App should not be a big problem because they are using the same APIs. I have all my devices set up with the Tuya App and switching to Smart Life would be a big hassle. Lots of devices with lots of automation.
Please, please consider extending this to Tuya App, too!
Or is there a way to adjust it in the source code? Probably not as it seems to be handled in the API gateway?

**Comment by shihuimiao** [comment]
> It seems, allowing Tuya App should not be a big problem because they are using the same APIs. I have all my devices set up with the Tuya App and switching to Smart Life would be a big hassle. Lots of devices with lots of automation. Please, please consider extending this to Tuya App, too! Or is there a way to adjust it in the source code? Probably not as it seems to be handled in the API gateway?

Tuya Smart Will support soon.

**Comment by HeMaN-NL** [comment]
Why did you close it, it has not been added yet i believe?

**Comment by labaland** [comment]
I just added this with my tuya app.

What is the difference if i change to smart life?
